export const calendario = {
    giornata1: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Empoli', team2: 'Verona', results: '0-1' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Frosinone', team2: 'Napoli', results: '1-3' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Genoa', team2: 'Fiorentina', results: '1-4' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Inter', team2: 'Monza', results: '2-0' },

        { numero: 5, day: 'dom', time: '12:30', team1: 'Roma', team2: 'Salernitana', results: '2-2' },
        { numero: 6, day: 'dom', time: '15:00', team1: 'Sassuolo', team2: 'Atalanta', results: '0-2' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Lecce', team2: 'Lazio', results: '2-1' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Udinese', team2: 'Juve', results: '0-3' },

        { numero: 9, day: 'lun', time: '18.00', team1: 'Torino', team2: 'Cagliari', results: '0-0' },
        { numero: 10, day: 'lun', time: '20:45', team1: 'Bologna', team2: 'Milan', results: '0-2' },
    ],
    giornata2: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Frosinone', team2: 'Atalanta', results: '2-1' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Monza', team2: 'Empoli', results: '2-0' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Verona', team2: 'Roma', results: '2-1' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Milan', team2: 'Torino', results: '4-1' },

        { numero: 5, day: 'dom', time: '12:30', team1: 'Fiorentina', team2: 'Lecce', results: '2-2' },
        { numero: 6, day: 'dom', time: '15:00', team1: 'Juve', team2: 'Bologna', results: '1-1' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Lazio', team2: 'Genoa', results: '0-1' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Napoli', team2: 'Sassuolo', results: '2-0' },

        { numero: 9, day: 'lun', time: '18.00', team1: 'Salernitana', team2: 'Udinese', results: '1-1' },
        { numero: 10, day: 'lun', time: '20:45', team1: 'Cagliari', team2: 'Inter', results: '0-2' },
    ],
    giornata3: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Sassuolo', team2: 'Verona', results: '3-1' },
        { numero: 2, day: 'ven', time: '18.30', team1: 'Roma', team2: 'Milan', results: '1-2' },

        { numero: 3, day: 'sab', time: '20.45', team1: 'Bologna', team2: 'Cagliari', results: '2-1' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Udinese', team2: 'Frosinone', results: '0-0' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Atalanta', team2: 'Monza', results: '3-0' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Napoli', team2: 'Lazio', results: '1-2' },

        { numero: 7, day: 'dom', time: '15:00', team1: 'Inter', team2: 'Fiorentina', results: '4-0' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Torino', team2: 'Genoa', results: '1-0' },
        { numero: 9, day: 'dom', time: '18.00', team1: 'Empoli', team2: 'Juve', results: '0-2' },
        { numero: 10, day: 'dom', time: '20:45', team1: 'Lecce', team2: 'Salernitana', results: '2-0' },
    ],
    giornata4: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Juve', team2: 'Lazio', results: '3-1' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Inter', team2: 'Milan', results: '5-1' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Genoa', team2: 'Napoli', results: '2-2' },

        { numero: 4, day: 'dom', time: '20:45', team1: 'Cagliari', team2: 'Udinese', results: '0-0' },
        { numero: 5, day: 'dom', time: '12:30', team1: 'Frosinone', team2: 'Sassuolo', results: '4-2' },
        { numero: 6, day: 'dom', time: '15:00', team1: 'Monza', team2: 'Lecce', results: '1-1' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Fiorentina', team2: 'Atalanta', results: '3-2' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Roma', team2: 'Empoli', results: '7-0' },

        { numero: 9, day: 'lun', time: '18.00', team1: 'Salernitana', team2: 'Torino', results: '0-3' },
        { numero: 10, day: 'lun', time: '20:45', team1: 'Verona', team2: 'Bologna', results: '0-0' },
    ],
    giornata5: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Salernitana', team2: 'Frosinone', results: '1-1' },
        { numero: 2, day: 'ven', time: '18.30', team1: 'Lecce', team2: 'Genoa', results: '1-0' },

        { numero: 3, day: 'sab', time: '20.45', team1: 'Milan', team2: 'Verona', results: '1-0' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Sassuolo', team2: 'Juve', results: '4-2' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Lazio', team2: 'Monza', results: '1-1' },

        { numero: 6, day: 'dom', time: '15:00', team1: 'Empoli', team2: 'Inter', results: '0-1' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Atalanta', team2: 'Cagliari', results: '2-0' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Udinese', team2: 'Fiorentina', results: '0-2' },
        { numero: 9, day: 'dom', time: '18.00', team1: 'Bologna', team2: 'Napoli', results: '0-0' },
        { numero: 10, day: 'dom', time: '20:45', team1: 'Torino', team2: 'Roma', results: '1-1' },
    ],
    giornata6: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Juve', team2: 'Lecce', results: '1-0' },

        { numero: 2, day: 'sab', time: '18.30', team1: 'Cagliari', team2: 'Milan', results: '1-3' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Empoli', team2: 'Salernitana', results: '1-0' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Verona', team2: 'Atalanta', results: '0-1' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Inter', team2: 'Sassuolo', results: '1-2' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Lazio', team2: 'Torino', results: '2-0' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Napoli', team2: 'Udinese', results: '4-1' },

        { numero: 8, day: 'dom', time: '18:00', team1: 'Frosinone', team2: 'Fiorentina', results: '1-1' },
        { numero: 9, day: 'dom', time: '18.00', team1: 'Monza', team2: 'Bologna', results: '0-0' },
        { numero: 10, day: 'dom', time: '20:45', team1: 'Genoa', team2: 'Roma', results: '4-1' },
    ],
    giornata7: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Lecce', team2: 'Napoli', results: '0-4' },
        { numero: 2, day: 'ven', time: '18.30', team1: 'Milan', team2: 'Lazio', results: '2-0' },
        { numero: 3, day: 'ven', time: '20.45', team1: 'Salernitana', team2: 'Inter', results: '0-4' },

        { numero: 4, day: 'ven', time: '20:45', team1: 'Bologna', team2: 'Empoli', results: '3-0' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Udinese', team2: 'Genoa', results: '2-2' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Atalanta', team2: 'Juve', results: '0-0' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Roma', team2: 'Frosinone', results: '2-0' },

        { numero: 8, day: 'sab', time: '18:00', team1: 'Sassuolo', team2: 'Monza', results: '0-1' },
        { numero: 9, day: 'dom', time: '18.00', team1: 'Torino', team2: 'Verona', results: '0-0' },
        { numero: 10, day: 'lun', time: '20:45', team1: 'Fiorentina', team2: 'Cagliari', results: '3-0' },
    ],
    giornata8: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Empoli', team2: 'Udinese', results: '0-0' },
        { numero: 2, day: 'ven', time: '18.30', team1: 'Lecce', team2: 'Sassuolo', results: '1-1' },

        { numero: 3, day: 'sab', time: '20.45', team1: 'Inter', team2: 'Bologna', results: '2-2' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Juve', team2: 'Torino', results: '2-0' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Genoa', team2: 'Milan', results: '0-1' },

        { numero: 6, day: 'dom', time: '15:00', team1: 'Monza', team2: 'Salernitana', results: '3-0' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Frosinone', team2: 'Verona', results: '2-1' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Lazio', team2: 'Atalanta', results: '3-2' },
        { numero: 9, day: 'dom', time: '18.00', team1: 'Cagliari', team2: 'Roma', results: '1-4' },
        { numero: 10, day: 'dom', time: '20:45', team1: 'Napoli', team2: 'Fiorentina', results: '1-3' },
    ],
    giornata9: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Verona', team2: 'Napoli', results: '1-3' },
        { numero: 2, day: 'ven', time: '18.30', team1: 'Torino', team2: 'Inter', results: '0-3' },
        { numero: 3, day: 'ven', time: '20.45', team1: 'Sassuolo', team2: 'Lazio', results: '0-2' },

        { numero: 4, day: 'ven', time: '20:45', team1: 'Roma', team2: 'Monza', results: '1-0' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Bologna', team2: 'Frosinone', results: '2-1' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Salernitana', team2: 'Cagliari', results: '2-2' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Atalanta', team2: 'Genoa', results: '2-0' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Milan', team2: 'Juve', results: '0-1' },

        { numero: 9, day: 'dom', time: '18.00', team1: 'Udinese', team2: 'Lecce', results: '1-1' },
        { numero: 10, day: 'lun', time: '20:45', team1: 'Fiorentina', team2: 'Empoli', results: '0-2' },
    ],
    giornata10: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Genoa', team2: 'Salernitana', results: '1-0' },

        { numero: 2, day: 'sab', time: '18.30', team1: 'Sassuolo', team2: 'Bologna', results: '1-1' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Lecce', team2: 'Torino', results: '0-1' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Juve', team2: 'Verona', results: '1-0' },

        { numero: 5, day: 'dom', time: '12:30', team1: 'Cagliari', team2: 'Frosinone', results: '4-3' },
        { numero: 6, day: 'dom', time: '15:00', team1: 'Monza', team2: 'Udinese', results: '1-1' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Inter', team2: 'Roma', results: '1-0' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Napoli', team2: 'Milan', results: '2-2' },

        { numero: 9, day: 'lun', time: '18.00', team1: 'Empoli', team2: 'Atalanta', results: '0-3' },
        { numero: 10, day: 'lun', time: '20:45', team1: 'Lazio', team2: 'Fiorentina', results: '1-0' },
    ],
    giornata11: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Bologna', team2: 'Lazio', results: '1-0' },

        { numero: 2, day: 'sab', time: '18.30', team1: 'Salernitana', team2: 'Napoli', results: '0-2' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Atalanta', team2: 'Inter', results: '1-2' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Milan', team2: 'Udinese', results: '0-1' },

        { numero: 5, day: 'dom', time: '12:30', team1: 'Verona', team2: 'Monza', results: '1-3' },
        { numero: 6, day: 'dom', time: '15:00', team1: 'Cagliari', team2: 'Genoa', results: '2-1' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Roma', team2: 'Lecce', results: '2-1' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Fiorentina', team2: 'Juve', results: '0-1' },

        { numero: 9, day: 'lun', time: '18.00', team1: 'Frosinone', team2: 'Empoli', results: '2-1' },
        { numero: 10, day: 'lun', time: '20:45', team1: 'Torino', team2: 'Sassuolo', results: '2-1' },
    ],
    giornata12: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Sassuolo', team2: 'Salernitana', results: '2-2' },
        { numero: 2, day: 'ven', time: '18.30', team1: 'Genoa', team2: 'Verona', results: '1-0' },

        { numero: 3, day: 'ven', time: '20.45', team1: 'Lecce', team2: 'Milan', results: '2-2' },
        { numero: 4, day: 'ven', time: '20:45', team1: 'Juve', team2: 'Cagliari', results: '2-1' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Monza', team2: 'Torino', results: '1-1' },

        { numero: 6, day: 'sab', time: '15:00', team1: 'Napoli', team2: 'Empoli', results: '0-1' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Fiorentina', team2: 'Bologna', results: '2-1' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Udinese', team2: 'Atalanta', results: '1-1' },
        { numero: 9, day: 'dom', time: '18.00', team1: 'Lazio', team2: 'Roma', results: '0-0' },
        { numero: 10, day: 'lun', time: '20:45', team1: 'Inter', team2: 'Frosinone', results: '2-0' },
    ],
    giornata13: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Salernitana', team2: 'Lazio', results: '2-1' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Atalanta', team2: 'Napoli', results: '1-2' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Milan', team2: 'Fiorentina', results: '1-0' },

        { numero: 4, day: 'dom', time: '20:45', team1: 'Cagliari', team2: 'Monza', results: '1-1' },
        { numero: 5, day: 'dom', time: '12:30', team1: 'Empoli', team2: 'Sassuolo', results: '3-4' },
        { numero: 6, day: 'dom', time: '15:00', team1: 'Frosinone', team2: 'Genoa', results: '2-1' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Roma', team2: 'Udinese', results: '3-1' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Juve', team2: 'Inter', results: '1-1' },

        { numero: 9, day: 'lun', time: '18.00', team1: 'Verona', team2: 'Lecce', results: '2-2' },
        { numero: 10, day: 'lun', time: '20:45', team1: 'Bologna', team2: 'Torino', results: '2-0' },
    ],
    giornata14: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Monza', team2: 'Juve', results: '1-2' },

        { numero: 2, day: 'sab', time: '18.30', team1: 'Genoa', team2: 'Empoli', results: '1-1' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Lazio', team2: 'Cagliari', results: '1-0' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Milan', team2: 'Frosinone', results: '3-1' },

        { numero: 5, day: 'dom', time: '12:30', team1: 'Lecce', team2: 'Bologna', results: '1-1' },
        { numero: 6, day: 'dom', time: '15:00', team1: 'Fiorentina', team2: 'Salernitana', results: '3-0' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Udinese', team2: 'Verona', results: '3-3' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Sassuolo', team2: 'Roma', results: '1-2' },
        { numero: 9, day: 'dom', time: '18.00', team1: 'Napoli', team2: 'Inter', results: '0-3' },

        { numero: 10, day: 'lun', time: '20:45', team1: 'Torino', team2: 'Atalanta', results: '3-0' },
    ],
    giornata15: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Juve', team2: 'Napoli', results: '1-0' },

        { numero: 2, day: 'sab', time: '18.30', team1: 'Verona', team2: 'Lazio', results: '1-1' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Atalanta', team2: 'Milan', results: '3-2' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Inter', team2: 'Udinese', results: '4-0' },

        { numero: 5, day: 'dom', time: '12:30', team1: 'Frosinone', team2: 'Torino', results: '0-0' },
        { numero: 6, day: 'dom', time: '15:00', team1: 'Monza', team2: 'Genoa', results: '1-0' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Salernitana', team2: 'Bologna', results: '1-2' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Roma', team2: 'Fiorentina', results: '1-1' },

        { numero: 9, day: 'lun', time: '18.00', team1: 'Empoli', team2: 'Lecce', results: '1-1' },
        { numero: 10, day: 'lun', time: '20:45', team1: 'Cagliari', team2: 'Sassuolo', results: '2-1' },
    ],
    giornata16: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Genoa', team2: 'Juve', results: '1-1' },

        { numero: 2, day: 'sab', time: '18.30', team1: 'Lecce', team2: 'Frosinone', results: '2-1' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Napoli', team2: 'Cagliari', results: '2-1' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Torino', team2: 'Empoli', results: '1-0' },

        { numero: 5, day: 'dom', time: '12:30', team1: 'Milan', team2: 'Monza', results: '3-0' },
        { numero: 6, day: 'dom', time: '15:00', team1: 'Fiorentina', team2: 'Verona', results: '1-0' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Udinese', team2: 'Sassuolo', results: '2-2' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Bologna', team2: 'Roma', results: '2-0' },
        { numero: 9, day: 'dom', time: '18.00', team1: 'Lazio', team2: 'Inter', results: '0-2' },

        { numero: 10, day: 'lun', time: '20:45', team1: 'Atalanta', team2: 'Salernitana', results: '4-1' },
    ],
    giornata17: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Empoli', team2: 'Lazio', results: '0-2' },
        { numero: 2, day: 'ven', time: '18.30', team1: 'Sassuolo', team2: 'Genoa', results: '1-2' },
        { numero: 3, day: 'ven', time: '20.45', team1: 'Monza', team2: 'Fiorentina', results: '0-1' },
        { numero: 4, day: 'ven', time: '20:45', team1: 'Salernitana', team2: 'Milan', results: '2-2' },

        { numero: 5, day: 'sab', time: '12:30', team1: 'Frosinone', team2: 'Juve', results: '1-2' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Bologna', team2: 'Atalanta', results: '1-0' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Torino', team2: 'Udinese', results: '1-1' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Verona', team2: 'Cagliari', results: '0-0' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Inter', team2: 'Lecce', results: '1-0' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Roma', team2: 'Napoli', results: '2-0' },
    ],
    giornata18: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Fiorentina', team2: 'Torino', results: '1-0' },
        { numero: 2, day: 'ven', time: '18.30', team1: 'Napoli', team2: 'Monza', results: '0-0' },
        { numero: 3, day: 'ven', time: '20.45', team1: 'Genoa', team2: 'Inter', results: '1-1' },
        { numero: 4, day: 'ven', time: '20:45', team1: 'Lazio', team2: 'Frosinone', results: '3-1' },

        { numero: 5, day: 'sab', time: '12:30', team1: 'Atalanta', team2: 'Lecce', results: '1-0' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Cagliari', team2: 'Empoli', results: '0-0' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Udinese', team2: 'Bologna', results: '3-0' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Verona', team2: 'Salernitana', results: '0-1' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Milan', team2: 'Sassuolo', results: '1-0' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Juve', team2: 'Roma', results: '1-0' },
    ],
    giornata19: [
        { numero: 1, day: 'ven', time: '18.30', team1: 'Bologna', team2: 'Genoa', results: '1-0' },

        { numero: 2, day: 'sab', time: '18.30', team1: 'Inter', team2: 'Verona', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Frosinone', team2: 'Monza', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Lecce', team2: 'Cagliari', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Sassuolo', team2: 'Fiorentina', results: '' },

        { numero: 6, day: 'dom', time: '15:00', team1: 'Empoli', team2: 'Milan', results: '' },
        { numero: 7, day: 'dom', time: '15:00', team1: 'Torino', team2: 'Napoli', results: '' },
        { numero: 8, day: 'dom', time: '18:00', team1: 'Udinese', team2: 'Lazio', results: '' },
        { numero: 9, day: 'dom', time: '18.00', team1: 'Salernitana', team2: 'Juve', results: '' },
        { numero: 10, day: 'dom', time: '20:45', team1: 'Roma', team2: 'Atalanta', results: '' },
    ],
    // -------------------------------------------------------------------------------------------------------
    giornata20: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Atalanta', team2: 'Frosinone', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Cagliari', team2: 'Bologna', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Fiorentina', team2: 'Udinese', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Genoa', team2: 'Torino', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Verona', team2: 'Empoli', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Juve', team2: 'Sassuolo', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Lazio', team2: 'Lecce', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Milan', team2: 'Roma', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Monza', team2: 'Inter', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Napoli', team2: 'Salernitana', results: '' },
    ],
    giornata21: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Bologna', team2: 'Fiorentina', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Empoli', team2: 'Monza', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Frosinone', team2: 'Cagliari', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Inter', team2: 'Atalanta', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Lecce', team2: 'Juve', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Roma', team2: 'Verona', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Salernitana', team2: 'Genoa', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Sassuolo', team2: 'Napoli', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Torino', team2: 'Lazio', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Udinese', team2: 'Milan', results: '' },
    ],
    giornata22: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Atalanta', team2: 'Udinese', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Cagliari', team2: 'Torino', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Fiorentina', team2: 'Inter', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Genoa', team2: 'Lecce', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Verona', team2: 'Frosinone', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Juve', team2: 'Empoli', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Lazio', team2: 'Napoli', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Milan', team2: 'Bologna', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Monza', team2: 'Sassuolo', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Salernitana', team2: 'Roma', results: '' },
    ],
    giornata23: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Atalanta', team2: 'Lazio', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Bologna', team2: 'Sassuolo', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Empoli', team2: 'Genoa', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Frosinone', team2: 'Milan', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Inter', team2: 'Juve', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Lecce', team2: 'Fiorentina', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Napoli', team2: 'Verona', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Roma', team2: 'Cagliari', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Torino', team2: 'Salernitana', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Udinese', team2: 'Monza', results: '' },
    ],
    giornata24: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Bologna', team2: 'Lecce', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Cagliari', team2: 'Lazio', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Fiorentina', team2: 'Frosinone', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Genoa', team2: 'Atalanta', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Juve', team2: 'Udinese', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Milan', team2: 'Napoli', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Monza', team2: 'Verona', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Roma', team2: 'Inter', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Salernitana', team2: 'Empoli', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Sassuolo', team2: 'Torino', results: '' },
    ],
    giornata25: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Atalanta', team2: 'Sassuolo', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Empoli', team2: 'Fiorentina', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Frosinone', team2: 'Roma', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Verona', team2: 'Juve', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Inter', team2: 'Salernitana', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Lazio', team2: 'Bologna', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Monza', team2: 'Milan', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Napoli', team2: 'Genoa', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Torino', team2: 'Lecce', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Udinese', team2: 'Cagliari', results: '' },
    ],
    giornata26: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Bologna', team2: 'Verona', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Cagliari', team2: 'Napoli', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Fiorentina', team2: 'Lazio', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Genoa', team2: 'Udinese', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Juve', team2: 'Frosinone', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Lecce', team2: 'Inter', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Milan', team2: 'Atalanta', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Roma', team2: 'Torino', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Salernitana', team2: 'Monza', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Sassuolo', team2: 'Empoli', results: '' },
    ],
    giornata27: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Atalanta', team2: 'Bologna', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Empoli', team2: 'Cagliari', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Frosinone', team2: 'Lecce', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Verona', team2: 'Sassuolo', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Inter', team2: 'Genoa', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Lazio', team2: 'Milan', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Monza', team2: 'Roma', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Napoli', team2: 'Juve', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Torino', team2: 'Fiorentina', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Udinese', team2: 'Salernitana', results: '' },
    ],
    giornata28: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Bologna', team2: 'Inter', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Cagliari', team2: 'Salernitana', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Fiorentina', team2: 'Roma', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Genoa', team2: 'Monza', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Juve', team2: 'Atalanta', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Lazio', team2: 'Udinese', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Lecce', team2: 'Verona', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Milan', team2: 'Empoli', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Napoli', team2: 'Torino', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Sassuolo', team2: 'Frosinone', results: '' },
    ],
    giornata29: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Atalanta', team2: 'Fiorentina', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Empoli', team2: 'Bologna', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Frosinone', team2: 'Lazio', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Verona', team2: 'Milan', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Inter', team2: 'Napoli', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Juve', team2: 'Genoa', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Monza', team2: 'Cagliari', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Roma', team2: 'Sassuolo', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Salernitana', team2: 'Lecce', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Udinese', team2: 'Torino', results: '' },
    ],
    giornata30: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Bologna', team2: 'Salernitana', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Cagliari', team2: 'Verona', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Fiorentina', team2: 'Milan', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Genoa', team2: 'Frosinone', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Inter', team2: 'Empoli', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Lazio', team2: 'Juve', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Lecce', team2: 'Roma', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Napoli', team2: 'Atalanta', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Sassuolo', team2: 'Udinese', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Torino', team2: 'Monza', results: '' },
    ],
    giornata31: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Cagliari', team2: 'Atalanta', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Empoli', team2: 'Torino', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Frosinone', team2: 'Bologna', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Verona', team2: 'Genoa', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Juve', team2: 'Fiorentina', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Milan', team2: 'Lecce', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Monza', team2: 'Napoli', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Roma', team2: 'Lazio', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Salernitana', team2: 'Sassuolo', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Udinese', team2: 'Inter', results: '' },
    ],
    giornata32: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Atalanta', team2: 'Verona', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Bologna', team2: 'Monza', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Fiorentina', team2: 'Genoa', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Inter', team2: 'Cagliari', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Lazio', team2: 'Salernitana', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Lecce', team2: 'Empoli', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Napoli', team2: 'Frosinone', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Sassuolo', team2: 'Milan', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Torino', team2: 'Juve', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Udinese', team2: 'Roma', results: '' },
    ],
    giornata33: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Cagliari', team2: 'Juve', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Empoli', team2: 'Napoli', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Genoa', team2: 'Lazio', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Verona', team2: 'Udinese', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Milan', team2: 'Inter', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Monza', team2: 'Atalanta', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Roma', team2: 'Bologna', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Salernitana', team2: 'Fiorentina', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Sassuolo', team2: 'Lecce', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Torino', team2: 'Frosinone', results: '' },
    ],
    giornata34: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Atalanta', team2: 'Empoli', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Bologna', team2: 'Udinese', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Fiorentina', team2: 'Sassuolo', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Frosinone', team2: 'Salernitana', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Genoa', team2: 'Cagliari', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Inter', team2: 'Torino', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Juve', team2: 'Milan', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Lazio', team2: 'Verona', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Lecce', team2: 'Monza', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Napoli', team2: 'Roma', results: '' },
    ],
    giornata35: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Cagliari', team2: 'Lecce', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Empoli', team2: 'Frosinone', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Verona', team2: 'Fiorentina', results: '' },
        { numero: 4, day: 'sab', time: '12:30', team1: 'Milan', team2: 'Genoa', results: '' },
        { numero: 5, day: 'sab', time: '15:00', team1: 'Monza', team2: 'Lazio', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Roma', team2: 'Juve', results: '' },
        { numero: 7, day: 'sab', time: '18:00', team1: 'Salernitana', team2: 'Atalanta', results: '' },
        { numero: 8, day: 'sab', time: '18.00', team1: 'Sassuolo', team2: 'Inter', results: '' },
        { numero: 9, day: 'sab', time: '20:45', team1: 'Torino', team2: 'Bologna', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Udinese', team2: 'Napoli', results: '' },
    ],
    giornata36: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Atalanta', team2: 'Roma', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Fiorentina', team2: 'Monza', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Frosinone', team2: 'Inter', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Genoa', team2: 'Sassuolo', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Verona', team2: 'Torino', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Juve', team2: 'Salernitana', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Lazio', team2: 'Empoli', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Lecce', team2: 'Udinese', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Milan', team2: 'Cagliari', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Napoli', team2: 'Bologna', results: '' },
    ],
    giornata37: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Bologna', team2: 'Juve', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Fiorentina', team2: 'Napoli', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Inter', team2: 'Lazio', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Lecce', team2: 'Atalanta', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Monza', team2: 'Frosinone', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Roma', team2: 'Genoa', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Salernitana', team2: 'Verona', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Sassuolo', team2: 'Cagliari', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Torino', team2: 'Milan', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Udinese', team2: 'Empoli', results: '' },
    ],
    giornata38: [
        { numero: 1, day: 'sab', time: '18.30', team1: 'Atalanta', team2: 'Torino', results: '' },
        { numero: 2, day: 'sab', time: '18.30', team1: 'Cagliari', team2: 'Fiorentina', results: '' },
        { numero: 3, day: 'sab', time: '20.45', team1: 'Empoli', team2: 'Roma', results: '' },
        { numero: 4, day: 'sab', time: '20:45', team1: 'Frosinone', team2: 'Udinese', results: '' },
        { numero: 5, day: 'sab', time: '12:30', team1: 'Genoa', team2: 'Bologna', results: '' },
        { numero: 6, day: 'sab', time: '15:00', team1: 'Verona', team2: 'Inter', results: '' },
        { numero: 7, day: 'sab', time: '15:00', team1: 'Juve', team2: 'Monza', results: '' },
        { numero: 8, day: 'sab', time: '18:00', team1: 'Lazio', team2: 'Sassuolo', results: '' },
        { numero: 9, day: 'sab', time: '18.00', team1: 'Milan', team2: 'Salernitana', results: '' },
        { numero: 10, day: 'sab', time: '20:45', team1: 'Napoli', team2: 'Lecce', results: '' },
    ],
}
// -------------------------------------------------------------------------------------- -------------------

export const giornataClou = calendario.giornata19;

// -------------------------------------------------------------------------------------- -------------------
